import Head from "next/head"
import Navbar from "../../Components/Navbar/Navbar"


//get static path
export const getStaticPaths = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts")
    const data = await res.json()

    const paths = data.map(element => {
        return {
            params: {
                pageno: element.id.toString(),
            }
        }
    })

    return {
        paths,
        fallback: false,
    }
}
//get static props
export const getStaticProps = async (context) => {
    const id = context.params.pageno
    const res = await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`)
    const data = await res.json()

    return {
        props: {
            data,
        }
    }
}

const SingleBlog = ({ data }) => {
    return (
        <div>
            <Head>
                <title>{data.title} </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="blogs">
                <h2 style={{ marginRight: "20px", color: "orange" }}>{data.id}</h2>
                <div>
                    <p style={{ fontSize: "20px", fontWeight: "bold" }}>{data.title}</p>
                    <p>{data.body}</p>
                </div>
            </div>
        </div>
    );
};

export default SingleBlog;