import Head from "next/head";
import Link from "next/link";
import Navbar from "../../Components/Navbar/Navbar";

// get api 
export const getStaticProps = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts")
    const data = await res.json()
    return {
        props: {
            data
        }
    }
}

const index = ({ data }) => {
    return (
        <div>
            <Head>
                <title>Blogs </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <h2 style={{ textAlign: "center", margin: "50px 0" }}>My Blog Page</h2>
            {
                data.slice(0, 5).map(element => {
                    return <div key={element.id} className="blogs">
                        <h2 style={{ marginRight: "5px", color: "orange" }}>{element.id}</h2>
                        <Link href={`/blog/${element.id}`}>
                            <p style={{ cursor: "pointer" }}>{element.title}</p>
                        </Link>
                    </div>
                })
            }
        </div>
    );
};

export default index;