import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../Components/Navbar/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Monib Bormon | Front-End Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <h2>Welcome Monib Bormon</h2>
      </main>
    </div>
  )
}
